################################
#### Django     ENVIRONMENT ####
################################
FROM python:3.9.21-slim-bullseye
ENV PYTHONUNBUFFERED 1
RUN mkdir /code
# RUN mkdir /build
WORKDIR /code

COPY ./shoe_watcher_backend/requirements.txt ./
RUN apt-get update && apt-get install -y libpq-dev && apt-get install -y gcc && pip install -r requirements.txt
COPY ./shoe_watcher_backend ./shoe_watcher_frontend ./
# COPY ./shoe_watcher_frontend/build ../build