FROM cnfldemos/cp-server-connect-datagen:0.6.2-7.5.0

RUN   confluent-hub install --no-prompt confluentinc/kafka-connect-jdbc:10.7.4 \
&& confluent-hub install --no-prompt debezium/debezium-connector-postgresql:2.2.1